[package]
name = "proc_helper_playground"
version = "0.1.0"
authors = ["Josh Cohen <joshuasteelers@me.com>"]
edition = "2018"

[dependencies]
syn = { version = "0.15", features = ["extra-traits", "full"] }
quote = "0.6"
proc-macro2 = "0.4"
